### ISSUE TITLE
Quickstart?

### ISSUE THREAD

**Issue by stela5** [just-containers/base-alpine#13]
Can you add a quickstart guide, like https://github.com/just-containers/s6-overlay#quickstart did for Ubuntu?

**Comment by glerchundi** [comment]
Hi @stela5, I don't want to duplicate documentation but maybe a simple quickstart would be ok:

```
FROM quay.io/justcontainers/base-alpine:v0.6.0
RUN apk add --update nginx && rm -rf /var/cache/apk/* && \
    echo "daemon off;" >> /etc/nginx/nginx.conf && mkdir /tmp/nginx
CMD ["nginx"]
```

**Comment by stela5** [comment]
Perfect, thanks!
