### ISSUE TITLE
Update Dockerfile to use official Alpine Linux image

### ISSUE THREAD

**Issue by stela5** [just-containers/base-alpine#14]
Now that https://registry.hub.docker.com/_/alpine/ exists, consider changing https://github.com/just-containers/base-alpine/blob/master/Dockerfile from `gliderlabs/alpine:3.1` to `alpine:latest`

**Comment by glerchundi** [comment]
Thanks @stela5 for pointing that out. I'm going to upgrade this to `3.2` and use the official repo because as stated in [this](https://github.com/gliderlabs/docker-alpine/issues/19#issuecomment-85667330) comment, both images differ in `apk-install` which is just a wrapper around `apk`.

/cc @jprjr

**Comment by glerchundi** [comment]
#15 should include these changes :-)
