### ISSUE TITLE
Update Alpine from 3.3 to 3.4

### ISSUE THREAD

**Issue by thoughtarray** [just-containers/base-alpine#26]
Alpine 3.3 has known vulnerabilities: https://hub.docker.com/r/library/alpine/tags/3.3/

Can we update to Alpine 3.4?

**Comment by glerchundi** [comment]
v0.12.0 should fit your needs ;)

**Comment by thoughtarray** [comment]
@glerchundi After reading your answer to #27, this makes sense.
