### ISSUE TITLE
Untagged builds on Docker Hub

### ISSUE THREAD

**Issue by thoughtarray** [just-containers/base-alpine#27]
Docker Hub lists many builds for base-alpine, but they aren't tagged.  Can an automated build be set up?

**Comment by glerchundi** [comment]
@thoughtarray we have an automated build but we decided to use quay as our official repo instead of docker hub

**Comment by thoughtarray** [comment]
Oh, I see.  So, are these Docker Images not primarily intended for public consumption?

**Comment by glerchundi** [comment]
@thoughtarray being hosted in quay doesn't mean it's not public consumption. Just that we decided to host in a different provider. I really like how CoreOS + Quay + Clair works instead of plain storage provided by Docker Hub.

**Comment by thoughtarray** [comment]
@glerchundi Okay, I didn't know Quay was public and free†.  I just saw a sign in wall and assumed it was a premium registry.  Thanks for the info.
